db-uri = "postgres://authenticator:password@127.0.0.1:54321/template1?sslmode=disable"
db-schemas = "api"
db-anon-role = "web_anon"
server-port = 3000

# Disable prepared statements (required for PGlite)
db-prepared-statements = false

# JWT verification (same secret as Auth)
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
